security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        App\Entity\User\User: bcrypt

    providers:

        in_memory: { memory: null }

        fos_userbundle:
            id: fos_user.user_provider.username
            
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern:  ^/authentication
            stateless: true
            anonymous: true
            provider:  app_user_provider
            json_login:
                check_path: /authentication_token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        api:
            pattern:   ^/api/             # protected path
            stateless: true
            provider:  app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                success_handler: sonata.user.google.authenticator.success_handler
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true
            switch_user:
                provider: fos_userbundle
                role: ROLE_ALLOWED_TO_SWITCH

        main_user:
            anonymous: lazy
            provider:  app_user_provider
            guard:
                authenticators:
                    - App\Security\User\LoginFormAuthenticator
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            json_login:
                username_path: email
                password_path: password
                check_path:     /account/login_check
            logout:
                path: app_logout
                target: /account/login
                delete_cookies: ['X-AUTH-TOKEN']

    access_control:
    
        - { path: ^/account/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: ROLE__USER }

        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:

        # ROLE_SONATA_USER_ADMIN_USER_HISTORY

        ROLE_ADMIN:                     [ROLE_USER]
        ROLE_SUPER_ADMIN:               [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_decision_manager:
        strategy: unanimous
