sonata_seo:
    encoding:         UTF-8
    page:

        title:            Sonata Platform
        default:          sonata.seo.page.default
        separator:        ' - '

        head:
            # 'xmlns':              http://www.w3.org/1999/xhtml
            # 'xmlns:og':           http://opengraphprotocol.org/schema/
            # 'xmlns:fb':           "http://www.facebook.com/2008/fbml"
    
        metas:
            charset:
                UTF-8:    ''

            name:
                # keywords:           default,meta,keywords # Depreciated and unused meta
                description:          This is the default description
                robots:               noindex, nofollow
                viewport:             width=device-width, initial-scale=1, shrink-to-fit=no

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                'X-UA-Compatible':      IE=EmulateIE7

            property:
                # Facebook application settings
                # 'fb:app_id':          XXXXXX
                # 'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                # 'og:site_name':       Sonata Project Sandbox
                # 'og:description':     A demo of the some rich bundles for your Symfony2 projects
                

