sonata_admin:
    title: 'Sonata Platform'
    title_logo: bundles/sonataadmin/logo_title.png

    global_search:
        empty_boxes: fade
    
    show_mosaic_button: true

    options:
        use_bootlint: false

    dashboard:
        blocks:
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
                        <p>This is a <code>sonata.block.service.text</code> from the Block
                        Bundle, you can create and add new block in these area by configuring
                        the <code>sonata_admin</code> section.</p> <br/> For instance, here
                        a RSS feed parser (<code>sonata.block.service.rss</code>):
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL]
                settings:
                    code:  sonata.media.admin.media     # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Médiathèque                  # static text or translation message
                    color: bg-red                       # colors: bg-green, bg-red and bg-aqua
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_MEDIA_ADMIN_GALLERY_ALL]
                settings:
                    code:  sonata.media.admin.gallery   # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Gallerie                     # static text or translation message
                    color: bg-green                     # colors: bg-green, bg-red and bg-aqua
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_USER_ADMIN_USER_ALL]
                settings:
                    code:  sonata.user.admin.user       # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Utilisateurs                 # static text or translation message
                    color: bg-aqua                      # colors: bg-green, bg-red and bg-aqua
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_USER_ADMIN_GROUP_ALL]
                settings:
                    code:  sonata.user.admin.group      # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Groupes                      # static text or translation message
                    color: bg-yellow                    # colors: bg-green, bg-red and bg-aqua
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_user]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_media]
            
        groups:
            sonata_media:
                label: Bibliothèque
                label_catalogue: SonataMediaBundle
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            sonata_user:
                label: Administration
                label_catalogue: SonataUserBundle
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_doctrine_orm_admin:

    templates:
        form:
            - "@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig"
        filter:
            - "@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig"
        types:
            list:
                array:      "@SonataAdmin/CRUD/list_array.html.twig"
                boolean:    "@SonataAdmin/CRUD/list_boolean.html.twig"
                date:       "@SonataAdmin/CRUD/list_date.html.twig"
                time:       "@SonataAdmin/CRUD/list_time.html.twig"
                datetime:   "@SonataAdmin/CRUD/list_datetime.html.twig"
                text:       "@SonataAdmin/CRUD/base_list_field.html.twig"
                trans:      "@SonataAdmin/CRUD/list_trans.html.twig"
                string:     "@SonataAdmin/CRUD/base_list_field.html.twig"
                smallint:   "@SonataAdmin/CRUD/base_list_field.html.twig"
                bigint:     "@SonataAdmin/CRUD/base_list_field.html.twig"
                integer:    "@SonataAdmin/CRUD/base_list_field.html.twig"
                decimal:    "@SonataAdmin/CRUD/base_list_field.html.twig"
                identifier: "@SonataAdmin/CRUD/base_list_field.html.twig"
                currency:   "@SonataAdmin/CRUD/list_currency.html.twig"
                percent:    "@SonataAdmin/CRUD/list_percent.html.twig"
                choice:     "@SonataAdmin/CRUD/list_choice.html.twig"
                url:        "@SonataAdmin/CRUD/list_url.html.twig"

            show:
                array:      "@SonataAdmin/CRUD/show_array.html.twig"
                boolean:    "@SonataAdmin/CRUD/show_boolean.html.twig"
                date:       "@SonataAdmin/CRUD/show_date.html.twig"
                time:       "@SonataAdmin/CRUD/show_time.html.twig"
                datetime:   "@SonataAdmin/CRUD/show_datetime.html.twig"
                text:       "@SonataAdmin/CRUD/base_show_field.html.twig"
                trans:      "@SonataAdmin/CRUD/show_trans.html.twig"
                string:     "@SonataAdmin/CRUD/base_show_field.html.twig"
                smallint:   "@SonataAdmin/CRUD/base_show_field.html.twig"
                bigint:     "@SonataAdmin/CRUD/base_show_field.html.twig"
                integer:    "@SonataAdmin/CRUD/base_show_field.html.twig"
                decimal:    "@SonataAdmin/CRUD/base_show_field.html.twig"
                currency:   "@SonataAdmin/CRUD/base_currency.html.twig"
                percent:    "@SonataAdmin/CRUD/base_percent.html.twig"
                choice:     "@SonataAdmin/CRUD/show_choice.html.twig"
                url:        "@SonataAdmin/CRUD/show_url.html.twig"
