sonata_admin:
    title: 'Sonata Platform'
    title_logo: bundles/sonataadmin/logo_title.png

    search: true
    global_search:
        empty_boxes: fade
    
    show_mosaic_button: true

    options:
        use_bootlint: false
        lock_protection: true

    dashboard:
        blocks:
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: >
                        <div class='panel panel-default'>
                            <div class='panel-heading'>
                                <h3 class='panel-title'>Welcome to the Sonata Admin</h3>
                            </div>
                            <div class='panel-body'>
                                <p>This is a <code>sonata.block.service.text</code> from the Block
                                Bundle, you can create and add new block in these area by configuring
                                the <code>sonata_admin</code> section.<br/> For instance, here
                                a RSS feed parser (<code>sonata.block.service.rss</code>):</p> 
                            </div>
                        </div>
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_USER_ALL]
                settings:
                    code:  sonata.user                  # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Utilisateurs                 # static text or translation message
                    color: bg-aqua                      # colors: bg-green, bg-red and bg-aqua
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL]
                settings:
                    code:  sonata.media.admin.media     # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Médiathèque                  # static text or translation message
                    color: bg-red                       # colors: bg-green, bg-red and bg-aqua
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_MEDIA_ADMIN_GALLERY_ALL]
                settings:
                    code:  sonata.media.admin.gallery   # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Gallerie                     # static text or translation message
                    color: bg-green                     # colors: bg-green, bg-red and bg-aqua
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_NUCLEOS_USER_ADMIN_ADMIN_USER_ALL]
                settings:
                    code:  nucleos_user_admin.admin.user # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Administrateurs              # static text or translation message
                    color: bg-aqua                      # colors: bg-green, bg-red and bg-aqua
            -
                class:    col-lg-3 col-xs-6             # twitter bootstrap responsive code
                position: top                           # zone in the dashboard
                type:     sonata.admin.block.stats      # block id
                roles: [ROLE_SUPER_ADMIN, ROLE_NUCLEOS_USER_ADMIN_ADMIN_GROUP_ALL]
                settings:
                    code:  nucleos_user_admin.admin.group # admin code - service id
                    icon:  fa-magic                     # font awesome icon
                    text:  Groupes                      # static text or translation message
                    color: bg-yellow                    # colors: bg-green, bg-red and bg-aqua
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [users]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [nucleos_user_admin]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_media]
            
        groups:
            users:
                label: Utilisateurs
                label_catalogue: Users
                items:
                    - sonata.user
            sonata_media:
                label: Bibliothèque
                label_catalogue: SonataMediaBundle
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            customize:
                label: Préférences
                label_catalogue: Customize
                items:
                    - sonata.maintenance
                    - sonata.redirect
            nucleos_user_admin:
                label: Administration
                label_catalogue: SonataUserBundle
                items:
                    - nucleos_user_admin.admin.user
                    - nucleos_user_admin.admin.group

    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    
    templates:
        user_block: '@NucleosUserAdmin/Admin/Core/user_block.html.twig'

sonata_doctrine_orm_admin:

    audit:
        force: false

sonata_exporter:
    exporter:
        default_writers:
            - json
            - xml
            - csv
            - xls
