twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    # cache: false # just for dev and testing
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
