parameters:

    # your sonata parameters here

services:

# User Admin
    sonata.user:
        class: App\Admin\User\UserAdmin
        arguments: [~, App\Entity\User\User, App\Controller\Admin\User\UserAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: users, label: Utilisateurs }
        public: true
    
# Maintenance Admin
    sonata.maintenance:
        class: App\Admin\MaintenanceAdmin
        arguments: [~, App\Entity\Configuration, App\Controller\Admin\MaintenanceAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: customize, label: Maintenance }

# Blocks for sonata admin
    sonata.block.service.custom.configuration:
        class: App\Service\Admin\Block\ConfigurationBlockService
        arguments:
            - '@twig'
            - ~
            - '@parameter_bag'
            - '@doctrine.orm.default_entity_manager'
            - '@cache.app'
            - '@request_stack'
            - '@router.default'
        tags:
            - { name: sonata.block }
            