services:

    #  service for override jwt token informations
    app.event.authentication_success_response:
        class: App\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    # service for KnpMenuBundle compatibility with symfony 4
    app.service.menu_builder:
        class: App\Service\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: header, alias: header }
            - { name: knp_menu.menu_builder, method: footer, alias: footer }
    
    # Service email notifications for User
    app.service.email_notifier:
        class: App\Service\Email\Notifier
        arguments: ['@mailer.mailer', '@parameter_bag', '@doctrine.orm.default_entity_manager']

    # Service email notifications for AdminUser
    app.service.email_admin_notifier:
        class: App\Service\Email\Notifier
        arguments: ['@mailer.mailer', '@parameter_bag', '@doctrine.orm.default_entity_manager', '@translator', '@router']

    # Service for configuration cache value
    app.service.cache.configuration_cache_builder:
        class: App\Service\Cache\ConfigurationCacheBuilder

    # Service for redirect cache value
    app.service.cache.redirect_cache_builder:
        class: App\Service\Cache\RedirectCacheBuilder
